apiVersion: v1
kind: Secret

metadata:
  name: dbsecret
  namespace: default

type: Opaque
data:
  db-username: dXNlcm5hbWU=  # echo -n 'username' | base64
  db-password: cGFzc3dvcmQ=  # echo -n 'password' | base64