apiVersion: v1
kind: Service

metadata:
  name: nginx-demo-dployment-nodeport-Service

spec:
  type: NodePort
  selector:
    app: nginx-demo-app3 #should match with pod labels
  ports:
    - name: http
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30009
