apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-demo-Deployment

spec:
  replicas: 2
  selector: 
    matchLabels:
      app: nginx-demo-app3
  template:
    metadata:
      name: nginx-demo-pod3
      labels:
        app: nginx-demo-app3
    spec:
      containers:
        - name: nginx-demo-container
          image: rudragajjala/nginx-demo:3.0.0
          ports:
            - containerPort: 80
    