apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-demo-replicaset
  labels:
    app: ngin-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx-demo-container
        image: rudragajjala/nginx-eks-demo:v1