apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: usermgmt-db-secrets
  namespace: default

spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "usermgmt-db-creds"
        objectType: "secretsmanager"
        jmesPath:
          - path: db_username
            objectAlias: dbusername
          - path: db_password
            objectAlias: dbpassword
  secretObjects:                
    - secretName: db-secrets-from-secrets-manager
      type: Opaque
      data:
        - objectName: dbusername
          key: db_username
        - objectName: dbpassword
          key: db_password