apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-create-service-deployment
  labels:
    app: user-create-microservice
    tier: backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-create-microservice
      tier: backend
  template:
    metadata:
      name: user-create-microservice-pod
      labels:
        app: user-create-microservice
        tier: backend
    spec:
      serviceAccountName: usermgmt-sa
      containers:
        - name: user-create-microservice-container
          image: rudragajjala/user-create-service:1.0.0
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            - name: DB_HOST
              value: psql-clusterip
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: usermgmt
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets-from-secrets-manager
                  key: db_username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets-from-secrets-manager
                  key: db_password
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          #livenessProbe: # Uncomment this section to use command based(nc -z) liveness probe
          #  exec:
          #    command:
          #    - sh
          #    - -c
          #    - nc -z localhost "3000"
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
    volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "usermgmt-db-secrets"
          