apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: ebs-pv-claim
  namespace: usermgmt

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 4Gi
  